language: ruby
dist: trusty
before_install:
  - gem install bundler
  - gem install yard
rvm: 
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

jobs:
  include:
    - stage: deploy documentation
      script: yard
      deploy:
        provider: pages
        local_dir: doc
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
