language: ruby
dist: trusty
before_install:
  - gem install bundler
  - gem install yard
rvm: 
  - 2.6
after_success:
  - yard
deploy:
  provider: pages
  local_dir: doc
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master