language: ruby
dist: trusty
before_install:
  - gem install bundler
  - gem install yard
  - chmod +x ci/check_rbi.sh
rvm: 
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

jobs:
  include:
    - stage: check RBI
      script: ./ci/check_rbi.sh
    - stage: deploy documentation
      script: yard
      deploy:
        provider: pages
        local_dir: doc
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
  allow_failures:
    - rvm: 2.3
    - rvm: ruby-head
