name: Run tests

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: "18 18 * * *"

jobs:
  test:
    strategy:
      matrix:
        ruby: [3.0, 3.1, 3.2]
    continue-on-error: false
      
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Check RBI is up-to-date
      run: ./ci/check_rbi.sh

  # Deploy documentation to GitHub Pages, if this is a push to master and the tests passed
  deploy-docs:
    if: ${{ github.ref == 'refs/heads/master' }}
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install dependencies
      run: bundle install
    - name: Build documentation
      run: bundle exec yard
    - name: Deploy to GitHub Actions
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{ secrets.BOT_PAT }}
        branch: gh-pages
        folder: doc
